# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_jtag.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] -quiet

# XDC: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/ip_0/constraints/jtag_axi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_jtag.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] -quiet

# XDC: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/ip_0/constraints/jtag_axi.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/test_xc7a25t_csg325.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
