# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/tom/git/TomKeddie/prj-artix7-pcie/fpga/test_xc7a25t_csg325/ex_des/pcie_7x_0_ex/imports/xilinx_pcie_7x_ep_x1g1.xdc

# IP: ip/pcie_7x_0/pcie_7x_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0} -quiet] -quiet
